DISCRIMINATOR:
  filters_disc: 512
  learning_rate_disc: 1e-8
EVAL:
  add_postprocessing_noise: true
  avg_pooling: true
  max_pooling: true
  num_batches: 256
  postprocessing_noise_factor: 1e-3
GENERAL:
  mode: GAN
  problem_type: normal
GENERATOR:
  filters_gen: 128
  latent_variables: 50
  learning_rate_gen: 1e-8
  noise_channels: 4
MODEL:
  architecture: forceconv
  padding: reflect
SETUP:
  log_folder: logfile/
TRAIN:
  CL_type: ensmeanMSE
  batch_size: 2
  content_loss_weight: 1000.0
  ensemble_size: 8
  kl_weight: 1e-8
  num_samples: 160000
  steps_per_checkpoint: 3200
  train_years:
  - 2021
  - 2022
  training_weights:
  - 0.4
  - 0.3
  - 0.2
  - 0.1
VAL:
  val_size: 8
  val_years: 2020
